#!/bin/sh

set -e

if dpkg-query -W -f='${Version}' wb-mqtt-homeui 2>/dev/null; then
    version=$(dpkg-query -W -f='${Version}' wb-mqtt-homeui)

    if dpkg --compare-versions "$version" "ge" "2.173.0"; then
        sed -i 's/"hide": *\(false\|true\)/"hide": true/' /usr/share/wb-mqtt-confed/schemas/wb-skirell-fluxa.schema.json
    else
        rm -f /usr/share/wb-mqtt-homeui/custom-menu/skirell-configurator.json
    fi
fi

CONFIG='wb-skirell-fluxa.conf'

if [ ! -f "/mnt/data/etc/$CONFIG" ]; then
   mv "/etc/$CONFIG" "/mnt/data/etc/$CONFIG"
fi

ln -Tfs "/mnt/data/etc/$CONFIG" "/etc/$CONFIG"

systemctl restart nginx.service

exit 0